name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libarchive-tools

      - name: Run the build script
        run: sudo ./build.sh

      - name: Upload disk image
        uses: actions/upload-artifact@v4
        with:
          name: arch-linux-arm-sp11.img
          path: build/arch-linux-arm-sp11.img